import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "flex-start",
    alignItems: "stretch",
    backgroundColor: "#f3f1fa",
    paddingTop: 32,
    paddingHorizontal: 0,
  },
  profileHeader: {
    alignItems: "center",
    marginBottom: 20,
    paddingTop: 12,
    paddingBottom: 16,
    backgroundColor: "#6b46c1",
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    elevation: 7,
    shadowColor: "#6b46c1",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
  },
  avatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#fff",
    marginBottom: 8,
    borderWidth: 2,
    borderColor: "#fff",
    elevation: 2,
  },
  name: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 4,
  },
  email: {
    fontSize: 15,
    color: "#e9e9e9",
    marginBottom: 2,
  },
  text: {
    fontSize: 20,
    textAlign: "center",
    margin: 10,
    color: "#6b46c1",
    fontWeight: "bold",
    letterSpacing: 1,
  },
});
