import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    justifyContent: "flex-start",
    alignItems: "stretch",
    backgroundColor: "#171923",
    paddingTop: 32,
    paddingHorizontal: 0,
    minHeight: '100%',
  },
  profileHeader: {
    alignItems: "center",
    marginBottom: 20,
    paddingTop: 12,
    paddingBottom: 16,
    backgroundColor: "rgba(107, 70, 193, 0.2)",
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    elevation: 7,
    borderWidth: 1,
    borderColor: "#6b46c1",
  },
  avatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    marginBottom: 8,
    borderWidth: 2,
    borderColor: "#6b46c1",
    elevation: 2,
  },
  name: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#ffffff",
    marginBottom: 4,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  email: {
    fontSize: 15,
    color: "rgba(255, 255, 255, 0.8)",
    marginBottom: 2,
  },
  text: {
    fontSize: 20,
    textAlign: "center",
    margin: 10,
    color: "#ffffff",
    fontWeight: "bold",
    letterSpacing: 1,
  },
});
